plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - README.md
  - LICENSE.md

title: Septem Circumstantiae
description: who, what, when, where, why, in what way, by what means
